import type { BandData } from "../types/MusicdleType";

export const BAND_DATABASE: BandData[] = [
  {
    id: "queen",
    name: "Queen",
    image: "https://i.scdn.co/image/ab6761610000517473e4d22612ac8d944b5789b4",
    format: "Banda",
    genres: ["Classic Rock", "Glam Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1970,
    membersCount: 4,
    topTrack: "Bohemian Rhapsody",
  },
  {
    id: "led-zeppelin",
    name: "Led Zeppelin",
    image: "https://i.scdn.co/image/b0248a44865493e6a03832aa89854ada16ff07a8",
    format: "Banda",
    genres: ["Hard Rock", "Heavy Metal", "Blues Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1968,
    membersCount: 4,
    topTrack: "Stairway to Heaven",
  },
  {
    id: "pink-floyd",
    name: "Pink Floyd",
    image: "https://i.scdn.co/image/ab676161000051743c9e8c67b087ba0cb5923b78",
    format: "Banda",
    genres: ["Progressive Rock", "Psychedelic Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1965,
    membersCount: 4,
    topTrack: "Comfortably Numb",
  },
  {
    id: "the-beatles",
    name: "The Beatles",
    image: "https://i.scdn.co/image/ab67616100005174357fdaf56c64a36a36741538",
    format: "Banda",
    genres: ["Classic Rock", "Pop Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1960,
    membersCount: 4,
    topTrack: "Hey Jude",
  },
  {
    id: "nirvana",
    name: "Nirvana",
    image: "https://i.scdn.co/image/a4e10b79a642e9891383448cbf37d7266a6883d6",
    format: "Trio",
    genres: ["Grunge", "Alternative Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1987,
    membersCount: 3,
    topTrack: "Smells Like Teen Spirit",
  },
  {
    id: "metallica",
    name: "Metallica",
    image: "https://i.scdn.co/image/ab6761610000517469ca98dd3083f1082d740e44",
    format: "Banda",
    genres: ["Heavy Metal", "Thrash Metal"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1981,
    membersCount: 4,
    topTrack: "Enter Sandman",
  },
  {
    id: "iron-maiden",
    name: "Iron Maiden",
    image: "https://i.scdn.co/image/ab67616100005174f9978ad4808f6f2723124d19",
    format: "Banda",
    genres: ["Heavy Metal"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1975,
    membersCount: 6,
    topTrack: "The Trooper",
  },
  {
    id: "ac-dc",
    name: "AC/DC",
    image: "https://i.scdn.co/image/ab67616100005174c4c77549095c86acb4e77b37",
    format: "Banda",
    genres: ["Hard Rock", "Heavy Metal"],
    country: "Austrália",
    flag: "🇦🇺",
    continent: "Oceania",
    formedYear: 1973,
    membersCount: 5,
    topTrack: "Back in Black",
  },
  {
    id: "guns-n-roses",
    name: "Guns N' Roses",
    image: "https://i.scdn.co/image/ab6761610000517450defaf9fc059a1efc541f4c",
    format: "Banda",
    genres: ["Hard Rock", "Heavy Metal"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1985,
    membersCount: 6,
    topTrack: "Sweet Child O' Mine",
  },
  {
    id: "linkin-park",
    name: "Linkin Park",
    image: "https://i.scdn.co/image/ab67616100005174527d95dabbe8b8b527e8136f",
    format: "Banda",
    genres: ["Nu Metal", "Alternative Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1996,
    membersCount: 6,
    topTrack: "In the End",
  },
  {
    id: "red-hot-chili-peppers",
    name: "Red Hot Chili Peppers",
    image: "https://i.scdn.co/image/ab67616100005174c33cc15260b767ddec982ce8",
    format: "Banda",
    genres: ["Funk Rock", "Alternative Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1983,
    membersCount: 4,
    topTrack: "Californication",
  },
  {
    id: "coldplay",
    name: "Coldplay",
    image: "https://i.scdn.co/image/ab676161000051741ba8fc5f5c73e7e9313cc6eb",
    format: "Banda",
    genres: ["Pop Rock", "Alternative Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1997,
    membersCount: 4,
    topTrack: "Yellow",
  },
  {
    id: "arctic-monkeys",
    name: "Arctic Monkeys",
    image: "https://i.scdn.co/image/ab676161000051747da39dea0a72f581535fb11f",
    format: "Banda",
    genres: ["Indie Rock", "Garage Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 2002,
    membersCount: 4,
    topTrack: "Do I Wanna Know?",
  },
  {
    id: "daft-punk",
    name: "Daft Punk",
    image: "https://i.scdn.co/image/ab67616100005174d3aa7cc0e419b6c459b08e8e",
    format: "Duo",
    genres: ["Eletrônica", "House", "Disco"],
    country: "França",
    flag: "🇫🇷",
    continent: "Europa",
    formedYear: 1993,
    membersCount: 2,
    topTrack: "Get Lucky",
  },
  {
    id: "gorillaz",
    name: "Gorillaz",
    image: "https://i.scdn.co/image/ab67616100005174dd5b57b40cf2aaeccd07835e",
    format: "Banda",
    genres: ["Alternative Rock", "Trip Hop", "Hip Hop"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1998,
    membersCount: 4,
    topTrack: "Feel Good Inc.",
  },
  {
    id: "green-day",
    name: "Green Day",
    image: "https://i.scdn.co/image/ab676161000051746ff0cd5ef2ecf733804984bb",
    format: "Trio",
    genres: ["Punk Rock", "Pop Punk"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1987,
    membersCount: 3,
    topTrack: "Boulevard of Broken Dreams",
  },
  {
    id: "foo-fighters",
    name: "Foo Fighters",
    image: "https://i.scdn.co/image/ab676161000051741db35bc9c01d2b1c151e44ce",
    format: "Banda",
    genres: ["Alternative Rock", "Hard Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1994,
    membersCount: 6,
    topTrack: "Everlong",
  },
  {
    id: "black-sabbath",
    name: "Black Sabbath",
    image: "https://i.scdn.co/image/ab67616100005174d109fa1e6b28ddfc5846cc4f",
    format: "Banda",
    genres: ["Heavy Metal", "Doom Metal"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1968,
    membersCount: 4,
    topTrack: "Paranoid",
  },
  {
    id: "oasis",
    name: "Oasis",
    image: "https://i.scdn.co/image/ab6761610000517423a08396d484aa0e81d73527",
    format: "Banda",
    genres: ["Britpop", "Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1991,
    membersCount: 5,
    topTrack: "Wonderwall",
  },
  {
    id: "slipknot",
    name: "Slipknot",
    image: "https://i.scdn.co/image/ab67616100005174f5bd8b1496eb4fb7ca5031ad",
    format: "Banda",
    genres: ["Nu Metal", "Heavy Metal"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1995,
    membersCount: 9,
    topTrack: "Psychosocial",
  },
  {
    id: "rammstein",
    name: "Rammstein",
    image: "https://i.scdn.co/image/ab6761610000517432845b1556f9dbdfe8ee6575",
    format: "Banda",
    genres: ["Industrial Metal", "Neue Deutsche Härte"],
    country: "Alemanha",
    flag: "🇩🇪",
    continent: "Europa",
    formedYear: 1994,
    membersCount: 6,
    topTrack: "Du Hast",
  },
  {
    id: "sepultura",
    name: "Sepultura",
    image: "https://i.scdn.co/image/ab6761610000517442b136165ba6ce25d2c1ebdc",
    format: "Banda",
    genres: ["Thrash Metal", "Groove Metal"],
    country: "Brasil",
    flag: "🇧🇷",
    continent: "América do Sul",
    formedYear: 1984,
    membersCount: 4,
    topTrack: "Roots Bloody Roots",
  },
  {
    id: "paramore",
    name: "Paramore",
    image: "https://i.scdn.co/image/ab67616100005174b10c34546a4ca2d7faeb8865",
    format: "Trio",
    genres: ["Pop Punk", "Alternative Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 2004,
    membersCount: 3,
    topTrack: "Misery Business",
  },
  {
    id: "evanescence",
    name: "Evanescence",
    image: "https://i.scdn.co/image/ab67616100005174f42c2c9bead41b262780ea89",
    format: "Banda",
    genres: ["Gothic Rock", "Alternative Metal"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1995,
    membersCount: 5,
    topTrack: "Bring Me to Life",
  },
  {
    id: "muse",
    name: "Muse",
    image: "https://i.scdn.co/image/ab67616100005174ccb215d769112ec422a59ce6",
    format: "Trio",
    genres: ["Alternative Rock", "Progressive Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1994,
    membersCount: 3,
    topTrack: "Uprising",
  },
  {
    id: "radiohead",
    name: "Radiohead",
    image: "https://i.scdn.co/image/ab67616100005174959527d2fabc9c64287e57b9",
    format: "Banda",
    genres: ["Alternative Rock", "Art Rock", "Eletrônica"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1985,
    membersCount: 5,
    topTrack: "Creep",
  },
  {
    id: "system-of-a-down",
    name: "System of a Down",
    image: "https://i.scdn.co/image/ab6761610000517460063d3451ade8f9fab397c2",
    format: "Banda",
    genres: ["Alternative Metal", "Nu Metal"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1994,
    membersCount: 4,
    topTrack: "Chop Suey!",
  },
  {
    id: "the-rolling-stones",
    name: "The Rolling Stones",
    image: "https://i.scdn.co/image/ab676161000051742b72b000ac948eba03bb3afe",
    format: "Banda",
    genres: ["Classic Rock", "Blues Rock"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1962,
    membersCount: 4,
    topTrack: "Paint It Black",
  },
  {
    id: "twenty-one-pilots",
    name: "Twenty One Pilots",
    image: "https://i.scdn.co/image/ab6761610000517461a7ea26d33ded218cd1e59d",
    format: "Duo",
    genres: ["Alternative Rock", "Indie Pop", "Hip Hop"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 2009,
    membersCount: 2,
    topTrack: "Stressed Out",
  },
  {
    id: "blink-182",
    name: "Blink-182",
    image: "https://i.scdn.co/image/ab676161000051745da36f8b98dd965336a1507a",
    format: "Trio",
    genres: ["Pop Punk", "Punk Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1992,
    membersCount: 3,
    topTrack: "All the Small Things",
  },
  {
    id: "the-strokes",
    name: "The Strokes",
    image: "https://i.scdn.co/image/ab6761610000517498856eea770468af6dd999d9",
    format: "Banda",
    genres: ["Indie Rock", "Garage Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1998,
    membersCount: 5,
    topTrack: "Last Nite",
  },
  {
    id: "the-cure",
    name: "The Cure",
    image: "https://i.scdn.co/image/ab67616100005174dd427c765c409ec02dc3a868",
    format: "Banda",
    genres: ["Post-Punk", "Gothic Rock", "New Wave"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1978,
    membersCount: 5,
    topTrack: "Boys Don't Cry",
  },
  {
    id: "david-bowie",
    name: "David Bowie",
    image: "https://i.scdn.co/image/ab67616100005174b78f77c5583ae99472dd4a49",
    format: "Solo",
    genres: ["Glam Rock", "Art Rock", "Pop"],
    country: "Reino Unido",
    flag: "🇬🇧",
    continent: "Europa",
    formedYear: 1962,
    membersCount: 1,
    topTrack: "Heroes",
  },
  {
    id: "michael-jackson",
    name: "Michael Jackson",
    image: "https://i.scdn.co/image/ab67616100005174997cc9a4aec335d46c9481fd",
    format: "Solo",
    genres: ["Pop", "R&B", "Disco"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1964,
    membersCount: 1,
    topTrack: "Billie Jean",
  },
  {
    id: "the-white-stripes",
    name: "The White Stripes",
    image: "https://i.scdn.co/image/ab6761610000517470cc06de8fc28226d4743cd9",
    format: "Duo",
    genres: ["Garage Rock", "Blues Rock"],
    country: "Estados Unidos",
    flag: "🇺🇸",
    continent: "América do Norte",
    formedYear: 1997,
    membersCount: 2,
    topTrack: "Seven Nation Army",
  },
  {
    id: "a-ha",
    name: "a-ha",
    image: "https://i.scdn.co/image/ab67616100005174294570977675d1359d07ce2c",
    format: "Trio",
    genres: ["Synthpop", "New Wave"],
    country: "Noruega",
    flag: "🇳🇴",
    continent: "Europa",
    formedYear: 1982,
    membersCount: 3,
    topTrack: "Take On Me",
  },
  {
    id: "legiao-urbana",
    name: "Legião Urbana",
    image: "https://i.scdn.co/image/d0a544a5f9e0a548536b9bc0449e50137e0dd08c",
    format: "Banda",
    genres: ["Rock Nacional", "Post-Punk"],
    country: "Brasil",
    flag: "🇧🇷",
    continent: "América do Sul",
    formedYear: 1982,
    membersCount: 4,
    topTrack: "Tempo Perdido",
  },
  {
    id: "tame-impala",
    name: "Tame Impala",
    image: "https://i.scdn.co/image/ab67616100005174e412a782245eb20d9626c601",
    format: "Solo",
    genres: ["Psychedelic Rock", "Indie Rock", "Synthpop"],
    country: "Austrália",
    flag: "🇦🇺",
    continent: "Oceania",
    formedYear: 2007,
    membersCount: 1,
    topTrack: "The Less I Know the Better",
  },
];
