import type { Album } from "../src/types/AlbumType/Album";

const BACKEND_URL = "";

export const ARTIST_MAP: Record<string, string[]> = {
  rock: [
    "Led Zeppelin",
    "Pink Floyd",
    "Queen",
    "The Rolling Stones",
    "AC/DC",
    "Jimi Hendrix",
    "Nirvana",
    "Foo Fighters",
    "The Beatles",
    "The Who",
    "Octorama",
    "Metallica",
    "Guns N' Roses",
    "Aerosmith",
    "Red Hot Chili Peppers",
    "Pearl Jam",
    "Soundgarden",
    "The Doors",
    "Deep Purple",
    "Black Sabbath",
    "Bon Jovi",
    "U2",
    "Maneskin",
    "Sepultura",
    "Ghost",
    "Rammstein",
    "The Clash",
    "Arctic Monkeys",
    "Blink-182",
    "Def Leppard",
    "Rush",
    "Radiohead",
    "David Bowie",
    "Bob Dylan",
    "Santana",
    "Fleetwood Mac",
    "Eagles",
    "Green Day",
    "Linkin Park",
    "Jimmy Page",
    "Kiss",
    "Lynyrd Skynyrd",
    "Van Halen",
    "The Police",
    "Journey",
    "The Kinks",
    "Yes",
    "King Crimson",
    "Iron Maiden",
    "Judas Priest",
    "Motörhead",
    "Steppenwolf",
    "Creedence Clearwater Revival",
    "Allman Brothers Band",
    "The Doors of Perception",
    "Black Flag",
    "Queensrÿche",
    "Megadeth",
    "Slayer",
    "Pantera",
    "Alice in Chains",
    "Soundgarden",
    "Tool",
    "Rage Against the Machine",
    "System of a Down",
    "Muse",
    "The White Stripes",
    "The Strokes",
    "Oasis",
    "Blur",
    "Radiohead",
    "Coldplay",
    "Imagine Dragons",
    "Paramore",
    "Evanescence",
    "Thirty Seconds to Mars",
    "Foo Fighters",
    "Kings of Leon",
    "The Smashing Pumpkins",
    "Pixies",
    "Nine Inch Nails",
    "The Cure",
    "Depeche Mode",
    "Panic! at the Disco",
    "My Chemical Romance",
    "Fall Out Boy",
    "Radiohead",
    "Arctic Monkeys",
    "The Black Crowes",
    "ZZ Top",
    "Whitesnake",
    "Foreigner",
    "Bad Company",
    "Chicago",
    "Santana",
    "Steve Miller Band",
    "Limp Bizkit",
    "Rammstein",
    "Marilyn Manson",
    "Alice Cooper",
    "Motley Crüe",
    "Def Leppard",
    "Scorpions",
    "Queensrÿche",
    "Journey",
    "Boston",
    "REO Speedwagon",
    "Toto",
    "Cheap Trick",
    "Yes",
    "Genesis",
    "Rush",
    "Kansas",
    "Emerson, Lake & Palmer",
    "The Moody Blues",
    "Deep Purple",
    "Uriah Heep",
    "Black Sabbath",
    "Led Zeppelin",
    "King Crimson",
    "Steely Dan",
    "Beastie Boys",
    "Rage Against The Machine",
    "The Offspring",
    "NOFX",
    "Bad Religion",
    "Social Distortion",
    "Blink-182",
    "Green Day",
    "Sum 41",
    "Good Charlotte",
    "The Rasmus",
    "Papa Roach",
    "Incubus",
    "System of a Down",
    "Linkin Park",
    "Papa Roach",
    "Disturbed",
    "Avenged Sevenfold",
  ],
  pop: [
    "Madonna",
    "Michael Jackson",
    "Beyoncé",
    "Taylor Swift",
    "Rihanna",
    "Lady Gaga",
    "Britney Spears",
    "Ariana Grande",
    "Katy Perry",
    "Dua Lipa",
    "Bruno Mars",
    "Justin Timberlake",
    "Ed Sheeran",
    "Selena Gomez",
    "Miley Cyrus",
    "The Weeknd",
    "Harry Styles",
    "Billie Eilish",
    "Olivia Rodrigo",
    "Doja Cat",
    "Charlie Puth",
    "Shawn Mendes",
    "Sam Smith",
    "Adele",
    "Lorde",
    "Camila Cabello",
    "Sia",
    "Halsey",
    "Carly Rae Jepsen",
    "Ellie Goulding",
    "Demi Lovato",
    "Nicki Minaj",
    "Christina Aguilera",
    "Jennifer Lopez",
    "Kesha",
    "Pink",
    "Kelly Clarkson",
    "Jason Derulo",
    "Meghan Trainor",
    "Maroon 5",
    "OneRepublic",
    "Imagine Dragons",
    "Ava Max",
    "Charli XCX",
    "Rita Ora",
    "Zara Larsson",
    "Tove Lo",
    "Bebe Rexha",
    "Celine Dion",
    "Whitney Houston",
    "Janet Jackson",
    "George Michael",
    "Prince",
    "Elton John",
    "Cher",
    "Gloria Estefan",
    "Backstreet Boys",
    "NSYNC",
    "Spice Girls",
    "Christina Perri",
    "Norah Jones",
    "Jessie J",
    "Leona Lewis",
    "Annie Lennox",
    "Shakira",
    "Enrique Iglesias",
    "Ricky Martin",
    "Alicia Keys",
    "John Legend",
    "Adele",
    "Sam Smith",
    "Troye Sivan",
    "Conan Gray",
    "Lana Del Rey",
    "Rina Sawayama",
    "Grimes",
    "Frank Ocean",
    "Lizzo",
    "Rosalía",
    "Måneskin",
    "Jonas Brothers",
    "Carly Rae Jepsen",
    "Hailee Steinfeld",
    "Tinashe",
    "Becky G",
    "Sabrina Carpenter",
    "Niall Horan",
    "ZAYN",
    "Louis Tomlinson",
    "Khalid",
    "Julia Michaels",
    "Alessia Cara",
    "BTS",
    "BLACKPINK",
    "TWICE",
    "SEVENTEEN",
    "NewJeans",
    "Charli XCX",
    "Troye Sivan",
    "Jessie Ware",
    "Janelle Monáe",
    "Florence + The Machine",
    "Rex Orange County",
    "Laufey",
  ],
  indie: [
    "Arctic Monkeys",
    "The Strokes",
    "Tame Impala",
    "Radiohead",
    "Vampire Weekend",
    "Florence + The Machine",
    "Imagine Dragons",
    "The 1975",
    "The Killers",
    "MGMT",
    "Two Door Cinema Club",
    "Foster The People",
    "Cage The Elephant",
    "Alt-J",
    "The Neighbourhood",
    "Phoenix",
    "The xx",
    "Of Monsters and Men",
    "Portugal. The Man",
    "M83",
    "The Lumineers",
    "Mumford & Sons",
    "Bastille",
    "Cold War Kids",
    "The Kooks",
    "Franz Ferdinand",
    "Bloc Party",
    "Foals",
    "Yeah Yeah Yeahs",
    "Interpol",
    "The National",
    "Bon Iver",
    "Lana Del Rey",
    "Beabadoobee",
    "Clairo",
    "Girl in Red",
    "Wallows",
    "The Drums",
    "Mac DeMarco",
    "Rex Orange County",
    "Dayglow",
    "Boy Pablo",
    "The Vaccines",
    "The Wombats",
    "Death Cab for Cutie",
    "The Shins",
    "CHVRCHES",
    "Beach House",
    "The War on Drugs",
    "Alvvays",
    "The Paper Kites",
    "Local Natives",
    "Grizzly Bear",
    "Fleet Foxes",
    "The Japanese House",
    "Men I Trust",
    "Temples",
    "BØRNS",
    "Haim",
    "King Princess",
    "Grouplove",
    "Passion Pit",
    "The Postal Service",
    "Sufjan Stevens",
    "The Kills",
    "Broken Bells",
    "The Fratellis",
    "The Coral",
    "Kaiser Chiefs",
    "Catfish and the Bottlemen",
    "The Vaccines",
    "Noah Kahan",
    "Matt Maeson",
    "Half•Alive",
    "The Strumbellas",
    "COIN",
    "Sir Chloe",
    "Glass Animals",
    "Wet Leg",
    "Billie Marten",
    "Gorillaz",
    "Metric",
    "Christine and the Queens",
    "Frou Frou",
    "Angus & Julia Stone",
    "Vance Joy",
    "Birdy",
    "James Bay",
    "Lord Huron",
    "Florence + The Machine",
    "Phoebe Bridgers",
    "Lucy Dacus",
    "Snail Mail",
    "Soccer Mommy",
    "Elliott Smith",
  ],
  "80s": ["A-ha", "Tears for Fears", "Duran Duran", "Prince", "Eurythmics"],
  metalcore: [
    "Bad Omens",
    "Axty",
    "Architects",
    "Bring Me The Horizon",
    "Parkway Drive",
    "Wage War",
    "Invent Animate",
    "Fit for a King",
    "Landmvrks",
    "Northlane",
    "Poppy",
    "Spiritbox",
    "While She Sleeps",
    "The Devil Wears Prada",
    "Bleed From Within",
    "Currents",
    "Silent Planet",
    "House Of Protection",
    "I Prevail",
    "Bullet For My Valentine",
    "As I Lay Dying",
    "Killswitch Engage",
    "Trivium",
    "August Burns Red",
    "Beartooth",
    "Motionless In White",
    "Erra",
    "Attila",
    "Polaris",
    "Bury Tomorrow",
    "Make Them Suffer",
    "Of Mice & Men",
    "Ice Nine Kills",
    "Born of Osiris",
    "Counterparts",
    "Veil of Maya",
    "Chelsea Grin",
    "Miss May I",
    "The Ghost Inside",
    "The Amity Affliction",
    "Atreyu",
    "Underoath",
    "Good Charlotte",
    "Sum 41",
    "Gideon",
    "In Hearts Wake",
    "Thornhill",
    "Void of Vision",
    "Windwaker",
  ],
};

async function getSpotifyToken(): Promise<string> {
  const response = await fetch(`${BACKEND_URL}/api/spotify-token`);

  if (!response.ok) {
    const errorData = await response.json();
    console.error("Erro ao obter token da API:", errorData);
    throw new Error(`Falha ao buscar token: ${response.statusText}`);
  }

  const data = await response.json();
  return data.access_token;
}

// Função para buscar álbuns no Spotify
export async function fetchAlbumsByGenre(
  genre: string,
  lastArtist: string | null = null
): Promise<Album[]> {
  const token = await getSpotifyToken();

  const artists = ARTIST_MAP[genre.toLowerCase()];
  if (!artists || artists.length === 0) {
    console.warn(`Nenhum artista encontrado para o gênero "${genre}".`);
    return [];
  }

  // Escolhe um artista aleatório diferente do anterior
  let randomArtist: string;
  do {
    randomArtist = artists[Math.floor(Math.random() * artists.length)];
  } while (randomArtist === lastArtist && artists.length > 1);

  const offset = Math.floor(Math.random() * 20);
  // const response = await fetch(
  //   `https://api.spotify.com/v1/search?q=${encodeURIComponent(
  //     randomArtist
  //   )}&type=album&limit=50&offset=${offset}`,
  //   {
  //     headers: { Authorization: `Bearer ${token}` },
  //   }
  // );

  const response = await fetch(
    `https://api.spotify.com/v1/search?q=$$${encodeURIComponent(
      randomArtist
    )}&type=album&limit=50&offset=${offset}`,
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );

  const data = await response.json();
  const retornoTratado: Album[] = data.albums?.items
    ?.filter((item: any) => item.album_type === "album")
    .filter((item: any) => artists.includes(item.artists[0]?.name))
    .map((item: any) => ({
      mbid: item.id,
      artist: item.artists[0]?.name ?? "Desconhecido",
      albumTitle: item.name,
      releaseYear: parseInt(item.release_date?.split("-")[0] ?? "0"),
      coverArtUrl: item.images?.[0]?.url ?? "",
      genre,
    }));

  //console.log(`Artista escolhido: ${randomArtist}`);
  return retornoTratado;
}
